// all products
export const productData = [
  {
    id: 12,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },
  {
    id: 19,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 28,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
  {
    id: 13,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },
  {
    id: 14,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },
  {
    id: 15,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },
  {
    id: 16,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },

  {
    id: 17,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },
  {
    id: 18,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },

  {
    id: 20,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 21,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 22,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 23,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 24,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 25,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 26,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 27,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },

  {
    id: 29,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
  {
    id: 30,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
  {
    id: 31,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
  {
    id: 32,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
  {
    id: 33,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
  {
    id: 34,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
];
//pending products

export const pendingProductData = [
  {
    id: 12,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },
  {
    id: 13,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },
  {
    id: 14,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },
  {
    id: 15,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },
  {
    id: 16,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },

  {
    id: 17,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },
  {
    id: 18,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "pending",
  },
];

//published products
export const publishedProductData = [
  {
    id: 19,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 20,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 21,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 22,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 23,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 24,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 25,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
  {
    id: 26,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "published",
  },
];

//expired
export const expiredProductData = [
  {
    id: 27,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
  {
    id: 28,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
  {
    id: 29,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
  {
    id: 30,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
  {
    id: 31,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
  {
    id: 32,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
  {
    id: 33,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
  {
    id: 34,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
    status: "expired",
  },
];

// images data
export const images = [
  {
    id: 1,
    img: "/bellefu/bellefu1.jpg",
  },
  {
    id: 2,
    img: "/bellefu/bellefu2.jpg",
  },
  {
    id: 3,
    img: "/bellefu/bellefu3.jpg",
  },
  {
    id: 4,
    img: "/bellefu/bellefu4.jpg",
  },
];
