export const productData = [
  {
    id: 12,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
  },
  {
    id: 13,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
  },
  {
    id: 14,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
  },
  {
    id: 15,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
  },
  {
    id: 16,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
  },

  {
    id: 17,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
  },
  {
    id: 18,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
  },
  {
    id: 19,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
  },
  {
    id: 20,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
  },
  {
    id: 21,
    Icon: "/productImage/product.jpg",
    title: "Product 1",
    price: 1500,
    state: "imo",
    country: "Nig",
  },
];
