import React from "react";
import Head from "next/head";
import Layout from "../../components/postAdsComponent/Layout";
import UnstyledSelectSimple1 from "../../components/postAdsComponent/CatInput";
import UnstyledSelectSimple2 from "../../components/postAdsComponent/SubCatInput";
import UnstyledSelectSimple3 from "../../components/postAdsComponent/CountrySelect";
import UnstyledSelectSimple4 from "../../components/postAdsComponent/State";
import UnstyledSelectSimple5 from "../../components/postAdsComponent/City";

function Index() {
  return (
    <div>
      <Head>
        <title>Bellefu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Overall container */}
      <div className=" shadow bg-bellefuWhite rounded-md  p-5">
        <div className="border  p-5 mt-7 ">
          <div>
            <form action="#" method="POST">
              <div className=" overflow-hidden sm:rounded-md">
                <div className="px-4 py-5 sm:p-6">
                  <div className="grid grid-cols-6 gap-6">
                    <div className="col-span-6 sm:col-span-3">
                      <label
                        for="first-name"
                        className="block text-sm font-medium text-gray-700"
                      >
                        Category
                      </label>
                      <UnstyledSelectSimple1/>
                    </div>

                    <div className="col-span-6 sm:col-span-3">
                      <label
                        for="last-name"
                        className="block  text-sm font-medium text-gray-700"
                      >
                        Sub-Category
                      </label>
                      <UnstyledSelectSimple2/>

                    </div>
                    <div className="col-span-6 sm:col-span-3">
                      <label
                        for="email"
                        className="block text-sm font-medium text-gray-700"
                      >
                        Country
                      </label>
                      <UnstyledSelectSimple3/>

                    </div>
                    <div className="col-span-6 sm:col-span-3">
                      <label
                        for="email"
                        className="block text-sm font-medium text-gray-700"
                      >
                        State
                      </label>
                      <UnstyledSelectSimple4/>

                    </div>
                    <div className="col-span-6 sm:col-span-3">
                      <label
                        for="email"
                        className="block text-sm font-medium text-gray-700"
                      >
                        City
                      </label>
                      <UnstyledSelectSimple5/>

                    </div>
                    <div className="col-span-6 sm:col-span-3">
                      <label
                        for="email"
                        className="block text-sm font-medium text-gray-700"
                      >
                        Location
                      </label>
                      <input
                      type="text"
                      name="location"
                      id="location"
                      autocomplete="given-name"
                      className=" bg-[white] p-[8px] mt-1 focus:ring-bellefuGreen focus:outline-0 block w-full shadow-sm sm:text-sm border-gray-300 border-2 rounded-md"
                    />
                    </div>
                  </div>
                </div>
              </div>
              
              <div className="p-5 flex justify-between">
                <button
                  type="submit"
                  class="flex justify-center items-center w-[15vw] py-2 px-4  shadow-sm text-sm font-medium rounded-md text-[black] bg-bellefuWhite  border hover:bg-[#e4e4e4] focus:outline-none focus:ring-2 focus:ring-offset-2 "
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  class="flex justify-center items-center w-[15vw] py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-bellefuOrange hover:bg-[#ffc253] focus:outline-none focus:ring-2 focus:ring-offset-2 "
                >
                  Save
                </button>
              </div>
            </form>
          </div>
        </div>


      </div>
    </div>
  );
}

Index.Layout = Layout;
export default Index;
