import React from "react";
import Head from "next/head";
import Layout from "../../components/postAdsComponent/Layout";


function Index() {
  return (
    <div>
      <Head>
        <title>Bellefu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Overall container */}
      <main className="bg-bellefuBackground h-screen overflow-hidden">
        <div className="max-w-7xl mx-auto">
          
          <div className="flex-1 min-h-screen">
            {/* <Body /> */}
          </div>
        </div>
      </main>
    </div>
  );
}

Index.Layout = Layout;
export default Index;